# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-23.11"
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/source/apidoc/ --private --module-first --separate birdy

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

conda:
  environment: environment-docs.yml
