# conda env create -f environment-docs.yml
name: birdy
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - nbsphinx
  - sphinx >=7.0.0
  - sphinx-codeautolink >=0.15.0
  - sphinx-copybutton >=0.5.2
