# conda env create -f environment-docs.yml
name: birdy
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - ipython >8.5.0,!=9.0.0
  - nbsphinx >=0.9.5
  - sphinx >=7.0.0,<8.2.0
  - sphinx-codeautolink >=0.16.0
  - sphinx-copybutton
